### ISSUE TITLE
Create an endpoint for health checkup e.g. /health-checkup in the server

### ISSUE THREAD

**Issue by ranjan-stha** [toggle-corp/ifrc-gates-backend#106]
Create an endpoint /health-checkup in the server. Check if the server can connect to the database and redis servers and return 200 if success.

**Comment by kopitek8** [comment]
@ranjan-stha, please look into it and move to done if completed

**Comment by ranjan-stha** [comment]
@bimal125 Currently I am hitting the /admin for the health checkup that returns 200. Could you create another health-checkup endpoint that tests the connectivity for the db and redis and (any other?)

**Comment by ranjan-stha** [comment]
This action is complete and used in the prod environment in aws.
