### ISSUE TITLE
Rework on finding top 5 highest and lowest countries

### ISSUE THREAD

**Issue by ranjan-stha** [toggle-corp/ifrc-gates-backend#122]
This is based on discussions with Bimal. Might need to assign this to Rup if needed.

Objective: To get top 5 highest and lowest countries based on applied filters.

The retrieved data needs to be fetched from `t_data_country_level_most_recent` if the indicator is selected(including other filters if any). The data needs to be the most recent if the indicator value exists for multiple months. Also, note that the indicator value that needs to be retrieved should be the first item of its sub-variables when alphabetically arranged per country (This should result in no duplicated data)

**Comment by kopitek8** [comment]
For bottom 5, the backend should not send 0 values data. 

If the value of a country is 0 in the database, disregard and skip it. Only send the values that are not 0.

`In Lowest Cases, do not show 0 or 0%. Instead, show countries with the least number of cases greater than 0. If it's a behavioral indicator and 0, show 0. Else, go with the initial statement.`

Please talk to me before starting work on this issue
