### ISSUE TITLE
Filter countries if it doesn't exist in t_countries table

### ISSUE THREAD

**Issue by ranjan-stha** [toggle-corp/ifrc-gates-backend#125]
Filter those countries whose records don't exist in the table `t_countries`. It might happen that the countries info exist in tables like `emergency_profile`, `t_data_country_level` etc but mayn't exist in `t_countries`. So simply ignore records of those countries. This is applicable in the filter options, charts, map, table etc.

**Comment by kopitek8** [comment]
Best if Cyrille handled in the database

**Comment by ranjan-stha** [comment]
Cyrille handled this issue in the db level.
