### ISSUE TITLE
Bug in dataCountryLevel

### ISSUE THREAD

**Issue by ranjan-stha** [toggle-corp/ifrc-gates-backend#140]
When ISO3 and indicator id are selected and if we change the iso3 then it might happen that the indicator_id is not present within that changed country, the backend should have returned null or something but it results in below error. 

Contact Shreeyash for more info.

![Image](https://user-images.githubusercontent.com/37866947/196392563-50f7e035-7e79-4472-a7bc-4eb37103e35e.png)

**Comment by thenav56** [comment]
@shreeyash07 Please provide error trackback (from console) and branch name as well.

**Comment by shreeyash07** [comment]
> @shreeyash07 Please provide error trackback (from console) and branch name as well.

Branch Name: feature/add-filter-is-twelve-month-data-country-level
Error is same as in screenshot provided

**Comment by shreeyash07** [comment]
@thenav56 @bimal125  bug is in dataCountryLevel. while providing wrong indicator_Id response should be empty array because in (MapModal)overview case indicator is selected first and then country

**Comment by thenav56** [comment]
@shreeyash07 Please pull and try again.

For the future, let's also share server-side logs as well if available. Look for Errors, Exceptions.

**Comment by ranjan-stha** [comment]
@thenav56 @shreeyash07 I guess this issue is fixed and merged with develop, right? May be we can move this card ?

**Comment by ranjan-stha** [comment]
confirmed by shreeyash, will be moved to done.
