### ISSUE TITLE
Edit dataGranular API with the description details only for Sources

### ISSUE THREAD

**Issue by kopitek8** [toggle-corp/ifrc-gates-backend#141]
- [ ] Add a Boolean field (distinct) which returns non-repeated results
- [ ] Order by source_date in DESC order

Example of the query:

```sql
SELECT DISTINCT source_date, title, emergency, organisation, link
FROM t_data_granular 
WHERE indicator_id = 'PRA003'
AND iso3 = 'USA'
ORDER BY source_date DESC
```

**Comment by k9845** [comment]
@kopitek8 What are the distinct fields here?
cc: @ranjan-stha

**Comment by ranjan-stha** [comment]
@k9845 : So we need to send the following DISTINCT fields: `title`, `organisation`, `source_date`, `link`,  `source_comment` based on the applied filters on iso3, indicator_id, subvariable(if any selected in dropdown)

Even if the field `source_comment` is null, just send null (not to ignore)

Ignore the field `category` (not to set Global)

Let me know if you have any issues:

cc @kopitek8
