### ISSUE TITLE
To add missing flag icons in the s3 bucket

### ISSUE THREAD

**Issue by ranjan-stha** [toggle-corp/ifrc-gates-backend#144]

**Comment by ranjan-stha** [comment]
Done for most of the countries. But still few are missing. We need to get it from Cyrille.

https://docs.google.com/spreadsheets/d/1y2mM9H-AILBta-A39ouzHskBl7Jn76gDEGKFv2fitG4/edit#gid=0

**Comment by ranjan-stha** [comment]
@kopitek8 let me know if Julien sends the flag icons for any country.

**Comment by ranjan-stha** [comment]
This action is complete. @Shhhhhubh check out but with low priority.

**Comment by ranjan-stha** [comment]
@Shhhhhubh did you get time to verify this? let me know

**Comment by ghost** [comment]
Yess! already verified all the counties have their respective flags

**Comment by ranjan-stha** [comment]
Closing this issue now.
