### ISSUE TITLE
To send additional data to the tooltip in Country Page.

### ISSUE THREAD

**Issue by ranjan-stha** [toggle-corp/ifrc-gates-backend#180]
In the Country Page, left side -> first card, the tool tip must show /send the data of the following indicators.

new_cases, new_cases_per_million, total_cases, new_deaths, total_deaths, new_deaths_per_million

Please contact Shreeyash to know which query is being used to fetch the current data. (Currently two contextual indicator ids are fetched e.g Deaths and Cases per Million.

This is the frontend issue:
https://github.com/collective-service/ifrc-gates-dashboard/issues/133

**Comment by k9845** [comment]
@shreeyash07 Will work on this and the data will now be fetched from a different table i.e `DataCountryLevelMostRecent`.
