### ISSUE TITLE
Filter out "interpolation - interpolation" in sources query

### ISSUE THREAD

**Issue by kopitek8** [toggle-corp/ifrc-gates-backend#203]
Source: filter out "Interpolation - Interpolation" needs to be filtered out so that it is not shown on the frontend

**Comment by ranjan-stha** [comment]
@k9845 Here's the query: 
select title, organisation, source_comment, source_date  from t_data_granular where title='Interpolation' and organisation = 'Interpolation'

These items need to be excluded at db level.

**Comment by ranjan-stha** [comment]
@bimal125 @k9845 @Rup-Narayan-Rajbanshi This task has been completed by Rup. Moving card to done.
