### ISSUE TITLE
Send all the subindicators in Country and Overview page

### ISSUE THREAD

**Issue by kopitek8** [toggle-corp/ifrc-gates-backend#206]
The Overview and Country page should have all the subindicators sent to them so that they can filter via subindicators themselves from the frontend

**Comment by ranjan-stha** [comment]
@Rup-Narayan-Rajbanshi please check if the backend is sending all the sub-indicators data/values to the frontend. In the Country Page, the sub-indicator values are being sent. In the Overview page, only the value of the first sub-indicator from the sorted list is being sent to the frontend. Please verify.
